
spring:

#  h2:
#    console:
#      enabled: true

  datasource:
#    url: jdbc:h2:mem:testdb
#    url: jdbc:h2:tcp://localhost/~/test
    url: jdbc:mysql://database-1.cbfvb7kgeitq.ap-northeast-2.rds.amazonaws.com/project1
#    driver-class-name: org.h2.Driver
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: admin
    password: 12345678

  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
#    defer-datasource-initialization: true

  devtools:
    livereload:
      enabled: true
  thymeleaf:
    suffix: .html
    cache: false
#    prefix: file:src/main/resources/templates/
